mod view;

pub use view::{
    ACTION_BUTTON_HEIGHT, CARD_PADDING, COLLAPSED_COLUMN_WIDTH, CredentialCardProps,
    HEADER_HEIGHT, LABEL_ROW_HEIGHT, SECTION_SPACING, USER_DROPDOWN_TOP_OFFSET, view,
};
